language: python
python:
    - "2.7"
# command to install dependencies
install:
    - pip install pytest pytest-cov
    - pip install pep8
    - pip install coveralls
    - pip install mockito
    - pip install radon
# command to run tests
script:
    - py.test --cov . --cov-report term-missing


after_success:
    - pep8 --first src
    - pep8 --first tests
    - pep8 --count src
    - pep8 --count tests


    - radon cc src
    - radon mi src
    - radon raw src
    - radon cc tests
    - radon mi tests
    - radon raw tests
    - coveralls

# email
notifications:
  email:
    recipients:
        - ale_luzu_15@hotmail.com
    on_failure: always


